services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: hospital
    volumes:
      - db-data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/01-setup.sql
      - ./populate.sql:/docker-entrypoint-initdb.d/02-populate.sql
    networks:
      - webnet

networks:
  webnet:

volumes:
  db-data:
